import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import OptionMenu from "./components/OptionMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TechKareer X clade",
  description: "Generated by create next ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div><Navbar />
        <OptionMenu /></div>
        {children}
        
        </body>
    </html>
  );
}
